import { Input } from '@nextui-org/react';
import { BsSearch } from 'react-icons/bs';

const RightBar = () => {
	return (
		<aside className='h-screen w-[30%] px-5 py-3 border-l'>
			<Input
				placeholder='Search Tweeter'
				size='md'
				color='primary'
				startContent={<BsSearch className=' mr-1 flex-shrink-0 ' />}
			/>
			<div className='h-[calc(100vh-65px)] overflow-y-scroll mt-3 py-1 border-t no-scrollbar'>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
				<h1>Hello</h1>
			</div>
		</aside>
	);
};
export default RightBar;
